#pragma once

#include <stdint.h>

/* XXX: Comment out this line for a non-test network */
//#define HSR_TEST_NETWORK

#define HSR_TEST_NETWORK_VERSION                            83 // autogenerated

#define HSR_BLOCKCHAIN_DATABASE_VERSION                     uint64_t( 201 )

/**
 *  The address prepended to string representation of
 *  addresses.
 *
 *  Changing these parameters will result in a hard fork.
 */
#define HSR_OLD_MULSIG_PREFIX								"h"
#define HSR_ADDRESS_PREFIX                                  "H"
#define HSR_BLOCKCHAIN_SYMBOL                               "HSR"
#define HSR_BLOCKCHAIN_NAME                                 "HSR"
#define HSR_BLOCKCHAIN_DESCRIPTION                          "hcash main network"
			
#define HSR_BLOCKCHAIN_PRECISION                            100000000

#define HSR_BLOCKCHAIN_MAX_UIA_MARKET_FEE                   10000
#define HSR_BLOCKCHAIN_BLOCK_INTERVAL_SEC                   int64_t(60)
#define HSR_BLOCKCHAIN_BLOCKS_PER_HOUR                      ((60*60)/HSR_BLOCKCHAIN_BLOCK_INTERVAL_SEC)
#define HSR_BLOCKCHAIN_BLOCKS_PER_DAY                       (HSR_BLOCKCHAIN_BLOCKS_PER_HOUR*int64_t(24))
#define HSR_BLOCKCHAIN_BLOCKS_PER_YEAR                      (HSR_BLOCKCHAIN_BLOCKS_PER_DAY*int64_t(365))

#define HSR_BLOCKCHAIN_NUM_DELEGATES                        uint32_t(9)
#define HSR_MAX_DELEGATE_PAY_PER_BLOCK                      int64_t( 1 * HSR_BLOCKCHAIN_PRECISION ) // 50 XTS
#define HSR_BLOCKCHAIN_MAX_UNDO_HISTORY                     HSR_BLOCKCHAIN_BLOCKS_PER_HOUR

#define HSR_BLOCKCHAIN_REGISTER_ACCOUNT_FEE                 int64_t( 10 * HSR_BLOCKCHAIN_PRECISION ) 

#define HSR_BLOCKCHAIN_MAX_SLATE_SIZE                       (HSR_BLOCKCHAIN_NUM_DELEGATES + (HSR_BLOCKCHAIN_NUM_DELEGATES/10))
#define HSR_BLOCKCHAIN_MAX_MESSAGE_SIZE                     2048
#define HSR_BLOCKCHAIN_MAX_FREE_MESSAGE_SIZE                1024
#define HSR_BLOCKCHAIN_MAX_SOFT_MAX_MESSAGE_SIZE            40
#define HSR_BLOCKCHAIN_MIN_MESSAGE_FEE_COE                  100
#define HSR_BLOCKCHAIN_MAX_TRANSACTION_EXPIRATION_SEC       (60*60*24*2)
#define HSR_BLOCKCHAIN_MAX_MEMO_SIZE                        19 // bytes
#define HSR_BLOCKCHAIN_EXTENDED_MEMO_SIZE                   32 // bytes
#define HSR_BLOCKCHAIN_MAX_EXTENDED_MEMO_SIZE               (HSR_BLOCKCHAIN_MAX_MEMO_SIZE + HSR_BLOCKCHAIN_EXTENDED_MEMO_SIZE)

#define HSR_DEFAULT_TRANSACTION_FEE                         1 // XTS
#define HSR_DEFAULT_TRANSACTION_EXPIRATION_SEC              (60*60)
#define HSR_DEFAULT_CONTRACT_MARGIN                         1 * HSR_BLOCKCHAIN_PRECISION 
#define HSR_PRODUCTE_BLOCK_INTERAL							60
#define HSR_ADJUST_DIFFICULTY_INTERAL						200
 // To decrease granularity of timestamp
 // Supposed to be 2^n-1
// i don't know why need this
#define HSR_STAKE_TIMESTAMP_MASK							15
#define POW_PROTOCOL_VERSION								80000
#define HSR_MIN_CHANGE_BALANCE_UPDATE_TIME					2 * HSR_BLOCKCHAIN_PRECISION
#define HSR_POS_BALANCE_PRODUCTE_INTERAL					50

/**
 *  The maximum amount that can be issued for user assets.
 *
 *  10^18 / 2^63 < 1  however, to support representing all share values as a double in
 *  languages like java script, we must stay within the epsilon so
 *
 *  10^15 / 2^53 < 1 allows all values to be represented as a double or an int64
 */
#define HSR_BLOCKCHAIN_MAX_SHARES                           (int64_t(3000)*int64_t(1000)*int64_t(1000)*int64_t(1000)*int64_t(1000)*int64_t(1000))

#define HSR_BLOCKCHAIN_MIN_NAME_SIZE                        1
#define HSR_BLOCKCHAIN_MAX_NAME_SIZE                        63
#define HSR_BLOCKCHAIN_MAX_NAME_DATA_SIZE                   (1024*64)

#define HSR_BLOCKCHAIN_MAX_SUB_SYMBOL_SIZE                  8 // characters
#define HSR_BLOCKCHAIN_MIN_SYMBOL_SIZE                      3 // characters
#define HSR_BLOCKCHAIN_MAX_SYMBOL_SIZE                      12 // characters

#define HSR_BLOCKCHAIN_MIN_BURN_FEE                         HSR_BLOCKCHAIN_PRECISION * 1 // 1 XTS

#ifdef HSR_TEST_NETWORK
#define HSR_BLOCKCHAIN_VOTE_UPDATE_PERIOD_SEC               10
#else
#define HSR_BLOCKCHAIN_VOTE_UPDATE_PERIOD_SEC               (60*60) // 1 hour
#endif

#define HSR_BLOCKCHAIN_MIN_FEEDS                            ((HSR_BLOCKCHAIN_NUM_DELEGATES/2) + 1)
#define HSR_BLOCKCHAIN_MINIMUM_SHORT_ORDER_SIZE             (HSR_BLOCKCHAIN_PRECISION*100)
#define HSR_BLOCKCHAIN_MIN_YIELD_PERIOD_SEC                 (60*60*24) // 24 hours
#define HSR_BLOCKCHAIN_MAX_YIELD_PERIOD_SEC                 (HSR_BLOCKCHAIN_BLOCKS_PER_YEAR * HSR_BLOCKCHAIN_BLOCK_INTERVAL_SEC) // 1 year

#ifdef HSR_TEST_NETWORK
#define HSR_BLOCKCHAIN_MAX_SHORT_PERIOD_SEC                 (2*60*60) // 2 hours
#else
#define HSR_BLOCKCHAIN_MAX_SHORT_PERIOD_SEC                 (30*24*60*60) // 1 month
#endif
#define HSR_BLOCKCHAIN_MAX_SHORT_APR_PCT                    (uint64_t(50))

#define HSR_BLOCKCHAIN_MCALL_D2C_NUMERATOR                  1
#define HSR_BLOCKCHAIN_MCALL_D2C_DENOMINATOR                2

// TODO: This stuff only matters for propagation throttling; should go somewhere else
#define HSR_BLOCKCHAIN_DEFAULT_RELAY_FEE                    1 // XTS
#define HSR_BLOCKCHAIN_MAX_TRX_PER_SECOND                   1000  // (1000)
#define HSR_BLOCKCHAIN_MAX_PENDING_QUEUE_SIZE               15000 // (HSR_BLOCKCHAIN_MAX_TRX_PER_SECOND * HSR_BLOCKCHAIN_BLOCK_INTERVAL_SEC)

#define HSR_BLOCKCHAIN_REVALIDATE_MAX_TRX_COUNT             (HSR_BLOCKCHAIN_MAX_TRX_PER_SECOND * HSR_BLOCKCHAIN_BLOCK_INTERVAL_SEC)


// for contract
#define  CONTRACT_ADDRESS_PREFIX "C" 
#define  SCRIPT_ID_PREFIX "S" 
#define  MULTI_ADDRESS_PREFIX "M"

#define  CONTRACT_MAX_BYTECODE_SIZE   (1 * 1024 * 1024)  //just set to the limit of block size
#define  CONTRACT_MAX_NAME_SIZE  32 
#define  CONTRACT_MAX_DESCRIPTION_SIZE  256
#define  LIMIT_PRICE 1
#define  CONTRACT_PARAM_MAX_LEN  1024

#define  CONTRACT_OFFLINE_LIMIT_MAX     (1024*1024*1024) 
#define  CONTRACT_TESTING_LIMIT_MAX     (1024*1024*1024) 

// for event
#define  EVENT_PARAM_MAX_LEN  1024
#define  EVENT_TYPE_MAX_LEN   256

#define HSR_BLOCKCHAIN_FREESIGNATURE_LIMIT	10
#define HSR_BLOCKCHAIN_MAX_SIGNAGTURE_NUM   1000
#define HSR_BLOCKCHAIN_EXTRA_SIGNATURE_FEE  1000
#define HSR_BLOCKCHAIN_TRANSACTION_MAX_DEPOSIT_NUM 100

